### ISSUE TITLE
Landing Editor error

### ISSUE THREAD

**Issue by WilhelmWas** [maxsite/landing#5]
1. Создаем новую страницу test (с одним файлом index.php).

2. http://site/test - видим страницу. Ok.

3. lpf-admin/editor/test/index.php - вызываем в редакторе. Ok.

4. сделав любое изменение в файле(читай: просто сохранив файл в редакторе) происходит замена в тексте ' => обратный слеш' т.е. кавычка заменяется на комментированную...

Пример:
< ?php if (!defined('BASEPATH')) exit('No direct script access allowed'); ? >
заменяется на:
< ?php if (!defined(обратный слеш'BASEPATHобратный слеш')) exit(обратный слеш'No direct script access allowedобратный слеш'); ? >

GitHub не выводит (обратный слеш), но я думаю понятно выразился:

если вместо одинарной кавычки поставить двойную, так же происходит замена на комментированный символ...

Где копать? Как победить?

С уважением Василий.

**Comment by maxsite** [comment]
Ну вроде как никаких замен в коде не производится. Я проверил. Тут либо дело в браузере (то есть передаца данных на уровне JS), либо в настройках PHP (добавляется экранирование спецсимволов). Уточните какие именно версии у вас?

**Comment by WilhelmWas** [comment]
вот я тут видео состряпал: удалил

пустил файл на загрузку, и пришлось срочно отлучиться, сразу ссылку не выслал :-(

Насчет версий: Win XP DE S3, и браузеры всех мастей :-) кроме ИЕ :-(
LPF - понятно, с сайта. Еще какие нужно данные... я не Марат Казей, я все скажу :-))


----- Original Message -----

**Comment by maxsite** [comment]
У нас яндекс блокируется, так что файл скачать не могу. Версия PHP какая?

**Comment by WilhelmWas** [comment]
и все же, почему я сразу об этом не подумал

if (is_file($fn = dirname(__FILE__) . '/index.php'))
{        
    $file = file_get_contents($fn);
    
    echo $file;
    
    file_put_contents($fn . '.txt', 'M\'Z_' . PHP_EOL . $file . '_M"Z' . PHP_EOL);
    
    $fn = file_get_contents($fn . '.txt');
    
    echo $fn;
}

else echo 'h1 Нету файла';


Вот такой скрипт работает как надо, т.е file_put_  все сохранил, без ошибок...
а то я в дороге, в мыслях, крутил будущее  письмо к хостеру, ан нет, на хосте пхп в порядке

PHP Version 5.3.29
  ----- Original Message -----

**Comment by maxsite** [comment]
Дело не в сохранение, а в том, что post-запрос сам делает экранирование. Это может происходить на уровне браузера, либо в php с параметром magic_quotes_gpc.

**Comment by WilhelmWas** [comment]
а эта инфа в чем то поможет?

phpinfo()

  ----- Original Message -----

**Comment by maxsite** [comment]
Скорее всего виноват magic_quotes_gpc. Нужно его в off поставить.

**Comment by WilhelmWas** [comment]
ЧЕЛОВЕК пишущий такой изумительный и чистый код - имеет чистую совесть :-)))
.
  ----- Original Message -----

**Comment by maxsite** [comment]
Отключайте magic_quotes_gpc на сервере.

**Comment by WilhelmWas** [comment]
Отлично, я думаю этот вопрос решится. Благодарю за оперативность и участие.
Не могу не выразить почтения программисту MAXу.
Изуметельный, грамотный и продуманный код выходит из под ваших пальчиков. Приятно читать и пользоваться.

БлагоДарю. Василий

Хари Ом
  ----- Original Message -----

**Comment by WilhelmWas** [comment]
Все, БлагоДарю. Вопрос решился.
Проблема была в [ magic_quotes_gpc=On ]
Сменил версию PHP и получил [ magic_quotes_gpc=Off ]
Теперь порядок, создает, редактирует, удаляет... Все без ошибок.
Вопрос снимается.
БлагоДарю **maxsite** за оперативную помощь
