### ISSUE TITLE
Часто появляющееся уведомление

### ISSUE THREAD

**Issue by jimmyjonezz** [maxsite/landing#6]
Давно не садился за код, но на скорую руку нужно было настроить одностраничный сайт. Все работает отлично, за исключением одного - появляется уведомление, по разным причинам. Специально не отлавливал и не записывал. Единственно, что записал, уведомление при очистке кэша.
Что-то серьезное?

Notice: Undefined index: users in C:\xampp\htdocs\landing\lpf-core\engine\additions\auth-session.php on line 293

**Comment by maxsite** [comment]
Как будто бы не видит опцию с именем юзера. Тут нужно как-то отлавливать эту ошибку. Возможно дело именно в кэше — страницы, где есть авторизация, кэширование нужно отключать.

**Comment by jimmyjonezz** [comment]
Кэширование отрубил. Теперь на всех страницах админки (главная, редактор, ...) и на сайте (хотя вышел из профиля админа) сверху страницы также красуется надпись: 
Notice: Undefined index: users in C:\xampp\htdocs\landing\lpf-core\engine\additions\auth-session.php on line 293

А при очистке кэша (когда он отключен), эта надпись появляется два раза.

Снова включил кэш. Теперь эта надпись появляется при очистке кэша, при создании нового файла (при этом файл не создается), при редактировании файлов в админке (при этом надпись появляется в самом редакторе, оформленная тегами)... интересно, что редактировании файла variables.php, эта надпись появляется два раза.

**Comment by maxsite** [comment]
Может неверно указал данные в auth-options.php ? У себя ошибку не могу воспроизвести...

**Comment by jimmyjonezz** [comment]
> Может неверно указал данные в auth-options.php ?

Нет, вместо логина и пароля записал свои значения. Один пользователь. Менял имя пользователя, менял пароль. Самое интересное, что с отключенным кэшем данная запись появляется на каждой странице...

**Comment by maxsite** [comment]
Если перед строчкой

`		if (is_array($OPTIONS['users']) and $OPTIONS['users'])`

Написать
`pr($OPTIONS);`

Что выводится?

**Comment by jimmyjonezz** [comment]
Array
(
    [username] => root
    [password] => root
    [users] => 
    [login_link] => login
    [logout_link] => logout
    [login_text] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-login-text.php
    [login_form] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin/auth/auth-login-form.php
    [text_error] => 

Incorect login/password

    [login_text_out] => Вход
    [login_text_error] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-login-text-error.php
    [file_post] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-post.php
    [file_login_ok] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-login.php
    [file_logout] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-logout.php
)
Array
(
    [username] => root
    [password] => root
    [users] => 
    [login_link] => login
    [logout_link] => logout
    [login_text] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-login-text.php
    [login_form] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin/auth/auth-login-form.php
    [text_error] => 
Incorect login/password

    [login_text_out] => Вход
    [login_text_error] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-login-text-error.php
    [file_post] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-post.php
    [file_login_ok] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-login.php
    [file_logout] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-logout.php
)
Array
(
    [username] => root
    [password] => root
    [users] => 
    [login_link] => login
    [logout_link] => logout
    [login_text] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-login-text.php
    [login_form] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin/auth/auth-login-form.php
    [text_error] => <div class="w300px b-center t-center t-white bg-red pad10 mar10-tb">Incorect login/password</div>
    [login_text_out] => <a href="?login">Вход</a>
    [login_text_error] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-login-text-error.php
    [file_post] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-post.php
    [file_login_ok] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-login.php
    [file_logout] => C:\xampp\htdocs\landing/lpf-content\pages\lpf-admin\auth/auth-r-logout.php
)

**Comment by maxsite** [comment]
Всё нормально. А если там же `pr($_SESSION);`.

**Comment by jimmyjonezz** [comment]
Тут тоже все нормально, передается массив из логина и пароля три(!?) раза. 
А почему в массиве значение поля "[users] =>" пустое? там что-то должно быть? true

Пробую параметр pr($OPTIONS['users']), получаю False.

Заметил, что в файле "variables", первой строчкой написано следующее: <b>Notice</b>:  Undefined index: users in <b>C:\xampp\htdocs\landing\lpf-core\engine\additions\auth-session.php</b> on line <b>293</b><br />

Так и должно быть?

**Comment by maxsite** [comment]
Массив users используется если нужно задать доступ нескольких пользователям. Судя по логу pr — все работает корректно. Почему вообще срабатывае эта ветка непонятно — if условие не должно работать, если users не массив. 

В variables.php не должно быть никаких ошибок.
